-- ════════════════════════════════════════════════════════════════
-- SUPERSEDED — do NOT paste this file.
--
-- An earlier version of this file revoked EXECUTE from `authenticated` on
-- functions that are actually called client-side / via user-JWT edge functions
-- (decrement_stock in POS, recompute_* in POS/Suppliers, sync_campaign_stats in
-- campaign-send, increment_api_usage in ai-assistant/business-brain/quick-tasks).
-- Applying it would have broken POS sales, supplier totals, campaign sending,
-- and AI usage tracking.
--
-- The CORRECT fix (DEFINER->INVOKER for client functions + PUBLIC revoke +
-- selective authenticated re-grant + avatars policy drop) lives in
--   supabase/schema-v18.sql
-- and has already been applied live to the project.
-- ════════════════════════════════════════════════════════════════
