-- ════════════════════════════════════════════════════════════════
-- Schema v10 (Profit Dashboard + Bank + Credit + GST) — run AFTER schema-v9
-- Adds: bank transactions, supplier/customer credit, GST fields, product cost
-- ════════════════════════════════════════════════════════════════

-- 1. Bank transactions table for statement imports
create table if not exists public.bank_transactions (
  id uuid not null generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  invoice_id uuid references public.invoices(id) on delete set null,
  transaction_date date not null,
  amount numeric(12,2) not null,
  description text,
  matched boolean default false,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 2. Enhance suppliers table with credit tracking
alter table public.suppliers add column if not exists credit_limit numeric(12,2) default 0;
alter table public.suppliers add column if not exists outstanding numeric(12,2) default 0;

-- 3. Enhance customers table with credit limits
alter table public.customers add column if not exists credit_limit numeric(12,2) default 0;
alter table public.customers add column if not exists outstanding numeric(12,2) default 0;

-- 4. Enhance invoices table with GST fields
alter table public.invoices add column if not exists gst_rate numeric(5,2) default 0;
alter table public.invoices add column if not exists gst_amount numeric(12,2) default 0;

-- 5. Enhance products table with cost tracking for profitability
alter table public.products add column if not exists cost numeric(12,2) default 0;

-- 6. Indexes for performance
create index if not exists idx_bank_transactions_user_id on public.bank_transactions(user_id);
create index if not exists idx_bank_transactions_invoice_id on public.bank_transactions(invoice_id);
create index if not exists idx_bank_transactions_date on public.bank_transactions(transaction_date);
create index if not exists idx_suppliers_outstanding on public.suppliers(outstanding desc nulls last);
create index if not exists idx_customers_outstanding on public.customers(outstanding desc nulls last);
create index if not exists idx_invoices_gst on public.invoices(gst_rate, gst_amount);

-- 7. RPC for recomputing supplier outstanding (called after PO changes)
create or replace function public.recompute_supplier_outstanding(supplier_uuid uuid)
returns void language plpgsql as
$$
begin
  update public.suppliers
  set outstanding = (
    select coalesce(sum(total_amount - (select coalesce(sum(amount), 0) from public.payments where invoice_id = public.invoices.id)), 0)
    from public.invoices
    where public.invoices.supplier_id = supplier_uuid
      and public.invoices.user_id = current_setting('app.current_user_id', true)::uuid
  )
  where public.suppliers.id = supplier_uuid;
end;
$$;

-- 8. RPC for recomputing customer outstanding
create or replace function public.recompute_customer_outstanding(customer_uuid uuid)
returns void language plpgsql as
$$
begin
  update public.customers
  set outstanding = (
    select coalesce(sum(total_amount), 0)
    from public.invoices
    where public.invoices.customer_id = customer_uuid
      and public.invoices.user_id = current_setting('app.current_user_id', true)::uuid
  )
  where public.customers.id = customer_uuid;
end;
$$;